"""
Metrics which should be tracked:

STT:
- real time factor
- utterance count

LLM:
- tokens/second
- input token count (output from stt + system prompt): chat history is disabled for simplicity for now
- output token count (number of tokens generated by llm)

TTS:
- rtf (synthesis time/audio duration)
- characters synthesized per second

Overall:
- total latency (user input/speech given, to the output audio)
- time taken by each component

System info:
- peak memory usage 
"""