"""
Metrics which should be tracked:

STT:
- real time factor (transcription_time / audio_duration)
- utterance count
- transcription latency (wall-clock: silence cutoff fires → on_transcript called)
  note: silence_cutoff_s=0.8 adds a fixed ~800ms to every turn not captured by RTF
- dropped utterances (on_transcript returns early because is_speaking=True)

LLM:
- tokens/second
- input token count (stt output + system prompt; chat history disabled for now)
- output token count (tokens generated by llm)
- truncation rate (how often response hits max_tokens=100 cap and gets cut off)

TTS:
- rtf (synthesis_time / audio_duration)
- characters synthesized per second
- audio duration generated (length of output audio in seconds)
- text truncation count (_clean_for_tts drops text after last sentence-ending punctuation)

Overall:
- total latency (user speech ends → output audio starts playing)
- time taken by each component (stt transcription, llm generate, tts synthesize)

System info:
- peak memory usage (rss via psutil)
- gpu/ane utilization (M4-specific; requires powermetrics or ioreg via subprocess)
- model load time per component (one-time at startup)
"""
